// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// @TODO: #med-p Update the currentPlatform to use the LLOO project. Whats' this used for?? Need we care the firestore ones are iOS??

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wiS37GJdy6l0e9nwr8vYGK6gUJ7Pke8',
    appId: '1:851215965679:android:d6166f32a15e2e71c9aa1a',
    messagingSenderId: '851215965679',
    projectId: 'lloo-mobile-staging',
    storageBucket: 'lloo-mobile-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXwr5W00UVoXHz0RAH7caNXPyqp_Z3_Nw',
    appId: '1:851215965679:ios:48497005173b0600c9aa1a',
    messagingSenderId: '851215965679',
    projectId: 'lloo-mobile-staging',
    storageBucket: 'lloo-mobile-staging.firebasestorage.app',
    iosBundleId: 'com.example.llooMobile.RunnerTests',
  );

  // Loaded explicitly as the firestore is on a different project
  static const FirebaseOptions firestoreFmDevOptions = FirebaseOptions(
    apiKey: 'AIzaSyDiabjHWSzZcaoWzec1w_IoaJDxQzLe-f4',
    appId: '1:777511957658:ios:07d139f3b90c72614b9b23',
    messagingSenderId: '777511957658',
    projectId: 'fm-dev-v1',
    storageBucket: 'fm-dev-v1.firebasestorage.app',
    iosBundleId: 'com.example.llooMobile.RunnerTests',
  );


  // Loaded explicitly as the firestore is on a different project
  static const FirebaseOptions firestoreLlooOptions = FirebaseOptions(
    apiKey: 'AIzaSyBuRde84gACf7ZH1sRSt795VI7iSvUD8ts',
    appId: '1:283447292458:ios:8ba7e3a2a0e82596a2c953',
    messagingSenderId: '283447292458',
    projectId: 'lloo-6913d',
    storageBucket: 'lloo-6913d.firebasestorage.app',
    iosBundleId: 'com.example.llooMobile.RunnerTests',
  );

}